In [8]:
from ucimlrepo import fetch_ucirepo 
bank_marketing = fetch_ucirepo(id=222) 

# data (as pandas dataframes) 
x = bank_marketing.data.features 
y = bank_marketing.data.targets 

# metadata 
print(bank_marketing.metadata) 

# variable information 
print(bank_marketing.variables)

{'uci_id': 222, 'name': 'Bank Marketing', 'repository_url': 'https://archive.ics.uci.edu/dataset/222/bank+marketing', 'data_url': 'https://archive.ics.uci.edu/static/public/222/data.csv', 'abstract': 'The data is related with direct marketing campaigns (phone calls) of a Portuguese banking institution. The classification goal is to predict if the client will subscribe a term deposit (variable y).', 'area': 'Business', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 45211, 'num_features': 16, 'feature_types': ['Categorical', 'Integer'], 'demographics': ['Age', 'Occupation', 'Marital Status', 'Education Level'], 'target_col': ['y'], 'index_col': None, 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 2014, 'last_updated': 'Fri Aug 18 2023', 'dataset_doi': '10.24432/C5K306', 'creators': ['S. Moro', 'P. Rita', 'P. Cortez'], 'intro_paper': {'ID': 277, 'type': 'NATIVE', 'title': 'A data-driven approach to predict the success of bank telemarketing', 'authors': 'Sérgio Moro, P. Cortez, P. Rita', 'venue': 'Decision Support Systems', 'year': 2014, 'journal': None, 'DOI': '10.1016/j.dss.2014.03.001', 'URL': 'https://www.semanticscholar.org/paper/cab86052882d126d43f72108c6cb41b295cc8a9e', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': None, 'pmcid': None}, 'additional_info': {'summary': "The data is related with direct marketing campaigns of a Portuguese banking institution. The marketing campaigns were based on phone calls. Often, more than one contact to the same client was required, in order to access if the product (bank term deposit) would be ('yes') or not ('no') subscribed. \n\nThere are four datasets: \n1) bank-additional-full.csv with all examples (41188) and 20 inputs, ordered by date (from May 2008 to November 2010), very close to the data analyzed in [Moro et al., 2014]\n2) bank-additional.csv with 10% of the examples (4119), randomly selected from 1), and 20 inputs.\n3) bank-full.csv with all examples and 17 inputs, ordered by date (older version of this dataset with less inputs). \n4) bank.csv with 10% of the examples and 17 inputs, randomly selected from 3 (older version of this dataset with less inputs). \nThe smallest datasets are provided to test more computationally demanding machine learning algorithms (e.g., SVM). \n\nThe classification goal is to predict if the client will subscribe (yes/no) a term deposit (variable y).", 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': 'Input variables:\n   # bank client data:\n   1 - age (numeric)\n   2 - job : type of job (categorical: "admin.","unknown","unemployed","management","housemaid","entrepreneur","student",\n                                       "blue-collar","self-employed","retired","technician","services") \n   3 - marital : marital status (categorical: "married","divorced","single"; note: "divorced" means divorced or widowed)\n   4 - education (categorical: "unknown","secondary","primary","tertiary")\n   5 - default: has credit in default? (binary: "yes","no")\n   6 - balance: average yearly balance, in euros (numeric) \n   7 - housing: has housing loan? (binary: "yes","no")\n   8 - loan: has personal loan? (binary: "yes","no")\n   # related with the last contact of the current campaign:\n   9 - contact: contact communication type (categorical: "unknown","telephone","cellular") \n  10 - day: last contact day of the month (numeric)\n  11 - month: last contact month of year (categorical: "jan", "feb", "mar", ..., "nov", "dec")\n  12 - duration: last contact duration, in seconds (numeric)\n   # other attributes:\n  13 - campaign: number of contacts performed during this campaign and for this client (numeric, includes last contact)\n  14 - pdays: number of days that passed by after the client was last contacted from a previous campaign (numeric, -1 means client was not previously contacted)\n  15 - previous: number of contacts performed before this campaign and for this client (numeric)\n  16 - poutcome: outcome of the previous marketing campaign (categorical: "unknown","other","failure","success")\n\n  Output variable (desired target):\n  17 - y - has the client subscribed a term deposit? (binary: "yes","no")\n', 'citation': None}}
           name     role         type      demographic  \
0           age  Feature      Integer              Age
1           job  Feature  Categorical       Occupation
2       marital  Feature  Categorical   Marital Status
3     education  Feature  Categorical  Education Level
4       default  Feature       Binary             None
5       balance  Feature      Integer             None
6       housing  Feature       Binary             None
7          loan  Feature       Binary             None
8       contact  Feature  Categorical             None
9   day_of_week  Feature         Date             None
10        month  Feature         Date             None
11     duration  Feature      Integer             None
12     campaign  Feature      Integer             None
13        pdays  Feature      Integer             None
14     previous  Feature      Integer             None
15     poutcome  Feature  Categorical             None
16            y   Target       Binary             None

                                          description  units missing_values
0                                                None   None             no
1   type of job (categorical: 'admin.','blue-colla...   None             no
2   marital status (categorical: 'divorced','marri...   None             no
3   (categorical: 'basic.4y','basic.6y','basic.9y'...   None             no
4                              has credit in default?   None             no
5                              average yearly balance  euros             no
6                                   has housing loan?   None             no
7                                  has personal loan?   None             no
8   contact communication type (categorical: 'cell...   None            yes
9                        last contact day of the week   None             no
10  last contact month of year (categorical: 'jan'...   None             no
11   last contact duration, in seconds (numeric). ...   None             no
12  number of contacts performed during this campa...   None             no
13  number of days that passed by after the client...   None            yes
14  number of contacts performed before this campa...   None             no
15  outcome of the previous marketing campaign (ca...   None            yes
16          has the client subscribed a term deposit?   None             no

In [9]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   age          45211 non-null  int64
 1   job          44923 non-null  object
 2   marital      45211 non-null  object
 3   education    43354 non-null  object
 4   default      45211 non-null  object
 5   balance      45211 non-null  int64
 6   housing      45211 non-null  object
 7   loan         45211 non-null  object
 8   contact      32191 non-null  object
 9   day_of_week  45211 non-null  int64
 10  month        45211 non-null  object
 11  duration     45211 non-null  int64
 12  campaign     45211 non-null  int64
 13  pdays        45211 non-null  int64
 14  previous     45211 non-null  int64
 15  poutcome     8252 non-null   object
dtypes: int64(7), object(9)
memory usage: 5.5+ MB

In [10]:
x.isnull().sum()

age                0
job              288
marital            0
education       1857
default            0
balance            0
housing            0
loan               0
contact        13020
day_of_week        0
month              0
duration           0
campaign           0
pdays              0
previous           0
poutcome       36959
dtype: int64

In [11]:
import warnings
warnings.filterwarnings('ignore')

In [12]:
x.drop_duplicates()

,age,job,marital,education,default,balance,housing,loan,contact,day_of_week,month,duration,campaign,pdays,previous,poutcome
0,58,management,married,tertiary,no,2143,yes,no,NaN,5,may,261,1,-1,0,NaN
1,44,technician,single,secondary,no,29,yes,no,NaN,5,may,151,1,-1,0,NaN
2,33,entrepreneur,married,secondary,no,2,yes,yes,NaN,5,may,76,1,-1,0,NaN
3,47,blue-collar,married,NaN,no,1506,yes,no,NaN,5,may,92,1,-1,0,NaN
4,33,NaN,single,NaN,no,1,no,no,NaN,5,may,198,1,-1,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,no,825,no,no,cellular,17,nov,977,3,-1,0,NaN
45207,71,retired,divorced,primary,no,1729,no,no,cellular,17,nov,456,2,-1,0,NaN
45208,72,retired,married,secondary,no,5715,no,no,cellular,17,nov,1127,5,184,3,success
45209,57,blue-collar,married,secondary,no,668,no,no,telephone,17,nov,508,4,-1,0,NaN
45210,37,entrepreneur,married,secondary,no,2971,no,no,cellular,17,nov,361,2,188,11,other

In [13]:
x.drop(columns=['contact','poutcome'],inplace=True)

In [14]:
x['education'].fillna(x['education'].mode()[0],inplace=True)
x['job'].fillna(x['job'].mode()[0],inplace=True)

In [15]:
x

,age,job,marital,education,default,balance,housing,loan,day_of_week,month,duration,campaign,pdays,previous
0,58,management,married,tertiary,no,2143,yes,no,5,may,261,1,-1,0
1,44,technician,single,secondary,no,29,yes,no,5,may,151,1,-1,0
2,33,entrepreneur,married,secondary,no,2,yes,yes,5,may,76,1,-1,0
3,47,blue-collar,married,secondary,no,1506,yes,no,5,may,92,1,-1,0
4,33,blue-collar,single,secondary,no,1,no,no,5,may,198,1,-1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,no,825,no,no,17,nov,977,3,-1,0
45207,71,retired,divorced,primary,no,1729,no,no,17,nov,456,2,-1,0
45208,72,retired,married,secondary,no,5715,no,no,17,nov,1127,5,184,3
45209,57,blue-collar,married,secondary,no,668,no,no,17,nov,508,4,-1,0
45210,37,entrepreneur,married,secondary,no,2971,no,no,17,nov,361,2,188,11

In [16]:
object_col = x.select_dtypes(include='object')
object_col

                job   marital  education default housing loan month
0        management   married   tertiary      no     yes   no   may
1        technician    single  secondary      no     yes   no   may
2      entrepreneur   married  secondary      no     yes  yes   may
3       blue-collar   married  secondary      no     yes   no   may
4       blue-collar    single  secondary      no      no   no   may
...             ...       ...        ...     ...     ...  ...   ...
45206    technician   married   tertiary      no      no   no   nov
45207       retired  divorced    primary      no      no   no   nov
45208       retired   married  secondary      no      no   no   nov
45209   blue-collar   married  secondary      no      no   no   nov
45210  entrepreneur   married  secondary      no      no   no   nov

[45211 rows x 7 columns]

In [17]:
from sklearn.preprocessing import LabelEncoder,MinMaxScaler
import joblib
encoder = {}
for i in object_col:
    lab_enc = LabelEncoder()
    x[i] = lab_enc.fit_transform(x[i])
    encoder[i] = lab_enc

In [18]:
x

,age,job,marital,education,default,balance,housing,loan,day_of_week,month,duration,campaign,pdays,previous
0,58,4,1,2,0,2143,1,0,5,8,261,1,-1,0
1,44,9,2,1,0,29,1,0,5,8,151,1,-1,0
2,33,2,1,1,0,2,1,1,5,8,76,1,-1,0
3,47,1,1,1,0,1506,1,0,5,8,92,1,-1,0
4,33,1,2,1,0,1,0,0,5,8,198,1,-1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,9,1,2,0,825,0,0,17,9,977,3,-1,0
45207,71,5,0,0,0,1729,0,0,17,9,456,2,-1,0
45208,72,5,1,1,0,5715,0,0,17,9,1127,5,184,3
45209,57,1,1,1,0,668,0,0,17,9,508,4,-1,0
45210,37,2,1,1,0,2971,0,0,17,9,361,2,188,11

In [19]:
min_max_scale = MinMaxScaler()
normalized_col = ['age','balance','duration']

x[normalized_col] = min_max_scale.fit_transform(x[normalized_col])

In [20]:
y.values.reshape(-1,)

array(['no', 'no', 'no', ..., 'yes', 'no', 'no'],
      shape=(45211,), dtype=object)

In [21]:
y = lab_enc.fit_transform(y)

In [22]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)

In [23]:
from sklearn.model_selection import  GridSearchCV
from sklearn.ensemble import RandomForestClassifier

In [24]:
paramgrid = {
    'n_estimators':[100,150,200],
    'max_depth':[4,5,8,3],
}

In [25]:
rf_model = RandomForestClassifier()

In [26]:
grid_model = GridSearchCV(estimator=rf_model,
                        param_grid= paramgrid,
                        cv= 5)

In [27]:
grid_model.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'max_depth': [4, 5, 8, 3],
                         'n_estimators': [100, 150, 200]})

In [28]:
grid_model.best_params_

{'max_depth': 8, 'n_estimators': 200}

In [29]:
y_pred = grid_model.predict(x_test)
y_pred[:10]

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [30]:
y_test[:10]

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [31]:
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(y_test,y_pred)*100

89.49424948392804

In [32]:
confusion_matrix(y_test,y_pred)

array([[11882,   114],
       [ 1311,   257]])

In [33]:
joblib.dump(grid_model,"rf_churn_model.pkl")

['rf_churn_model.pkl']

In [34]:
from sklearn.model_selection import RandomizedSearchCV
random_model = RandomizedSearchCV(estimator=rf_model,param_distributions=paramgrid)

In [35]:
random_model.fit(x_train,y_train)

RandomizedSearchCV(estimator=RandomForestClassifier(),
                   param_distributions={'max_depth': [4, 5, 8, 3],
                                        'n_estimators': [100, 150, 200]})

In [ ]:
y_pred = random_model.predict(x_train,y_train)
y_pred[:10]

In [ ]:
y_pred[:10]

In [ ]:
accuracy_score(y_test,y_pred)*100

In [36]:
from xgboost import XGBClassifier
paramgrid = {
    'estimaters':[100,150,200],
    'max_depth':[5,10,15]
}

In [39]:
xgboost = XGBClassifier()
xgrid_model = GridSearchCV(estimator=xgboost,param_grid=paramgrid,cv = 5)

In [40]:
xgrid_model.fit(x_train,y_train)

GridSearchCV(cv=5,
             estimator=XGBClassifier(base_score=None, booster=None,
                                     callbacks=None, colsample_bylevel=None,
                                     colsample_bynode=None,
                                     colsample_bytree=None, device=None,
                                     early_stopping_rounds=None,
                                     enable_categorical=False, eval_metric=None,
                                     feature_types=None, feature_weights=None,
                                     gamma=None, grow_policy=None,
                                     importance_type=None,
                                     interaction_constraints=None,
                                     learning_rate=None, max_bin=None,
                                     max_cat_threshold=None,
                                     max_cat_to_onehot=None,
                                     max_delta_step=None, max_depth=None,
                                     max_leaves=None, min_child_weight=None,
                                     missing=nan, monotone_constraints=None,
                                     multi_strategy=None, n_estimators=None,
                                     n_jobs=None, num_parallel_tree=None, ...),
             param_grid={'estimaters': [100, 150, 200],
                         'max_depth': [5, 10, 15]})

In [42]:
y_pred = xgrid_model.predict(x_test)
y_pred[:10]

array([0, 0, 0, 0, 1, 1, 0, 0, 0, 0])

In [43]:
y_test[:10]

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [ ]:
accuracy_score(y_test,y_pred)*100

0.901135358301386

In [47]:
from sklearn.ensemble import AdaBoostClassifier
adaboost = AdaBoostClassifier(estimator=rf_model,
                            n_estimators=100,
                            learning_rate=1)

In [48]:
adaboost.fit(x_train,y_train)

AdaBoostClassifier(estimator=RandomForestClassifier(), learning_rate=1,
                   n_estimators=100)

In [50]:
y_pred = adaboost.predict(x_test)
y_pred[:10]

array([0, 0, 0, 0, 1, 1, 0, 0, 0, 0])

In [51]:
y_test[:10]

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [ ]:
accuracy_score(y_test,y_pred)*100

0.9006930109112357