In [48]:
from ucimlrepo import fetch_ucirepo 
bank_marketing = fetch_ucirepo(id=222)

In [49]:
# data (as pandas dataframes) 
x = bank_marketing.data.features 
y = bank_marketing.data.targets 

# metadata 
print(bank_marketing.metadata) 

# variable information 
print(bank_marketing.variables)

{'uci_id': 222, 'name': 'Bank Marketing', 'repository_url': 'https://archive.ics.uci.edu/dataset/222/bank+marketing', 'data_url': 'https://archive.ics.uci.edu/static/public/222/data.csv', 'abstract': 'The data is related with direct marketing campaigns (phone calls) of a Portuguese banking institution. The classification goal is to predict if the client will subscribe a term deposit (variable y).', 'area': 'Business', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 45211, 'num_features': 16, 'feature_types': ['Categorical', 'Integer'], 'demographics': ['Age', 'Occupation', 'Marital Status', 'Education Level'], 'target_col': ['y'], 'index_col': None, 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 2014, 'last_updated': 'Fri Aug 18 2023', 'dataset_doi': '10.24432/C5K306', 'creators': ['S. Moro', 'P. Rita', 'P. Cortez'], 'intro_paper': {'ID': 277, 'type': 'NATIVE', 'title': 'A data-driven approach to predict the success of bank telemarketing', 'authors': 'Sérgio Moro, P. Cortez, P. Rita', 'venue': 'Decision Support Systems', 'year': 2014, 'journal': None, 'DOI': '10.1016/j.dss.2014.03.001', 'URL': 'https://www.semanticscholar.org/paper/cab86052882d126d43f72108c6cb41b295cc8a9e', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': None, 'pmcid': None}, 'additional_info': {'summary': "The data is related with direct marketing campaigns of a Portuguese banking institution. The marketing campaigns were based on phone calls. Often, more than one contact to the same client was required, in order to access if the product (bank term deposit) would be ('yes') or not ('no') subscribed. \n\nThere are four datasets: \n1) bank-additional-full.csv with all examples (41188) and 20 inputs, ordered by date (from May 2008 to November 2010), very close to the data analyzed in [Moro et al., 2014]\n2) bank-additional.csv with 10% of the examples (4119), randomly selected from 1), and 20 inputs.\n3) bank-full.csv with all examples and 17 inputs, ordered by date (older version of this dataset with less inputs). \n4) bank.csv with 10% of the examples and 17 inputs, randomly selected from 3 (older version of this dataset with less inputs). \nThe smallest datasets are provided to test more computationally demanding machine learning algorithms (e.g., SVM). \n\nThe classification goal is to predict if the client will subscribe (yes/no) a term deposit (variable y).", 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': 'Input variables:\n   # bank client data:\n   1 - age (numeric)\n   2 - job : type of job (categorical: "admin.","unknown","unemployed","management","housemaid","entrepreneur","student",\n                                       "blue-collar","self-employed","retired","technician","services") \n   3 - marital : marital status (categorical: "married","divorced","single"; note: "divorced" means divorced or widowed)\n   4 - education (categorical: "unknown","secondary","primary","tertiary")\n   5 - default: has credit in default? (binary: "yes","no")\n   6 - balance: average yearly balance, in euros (numeric) \n   7 - housing: has housing loan? (binary: "yes","no")\n   8 - loan: has personal loan? (binary: "yes","no")\n   # related with the last contact of the current campaign:\n   9 - contact: contact communication type (categorical: "unknown","telephone","cellular") \n  10 - day: last contact day of the month (numeric)\n  11 - month: last contact month of year (categorical: "jan", "feb", "mar", ..., "nov", "dec")\n  12 - duration: last contact duration, in seconds (numeric)\n   # other attributes:\n  13 - campaign: number of contacts performed during this campaign and for this client (numeric, includes last contact)\n  14 - pdays: number of days that passed by after the client was last contacted from a previous campaign (numeric, -1 means client was not previously contacted)\n  15 - previous: number of contacts performed before this campaign and for this client (numeric)\n  16 - poutcome: outcome of the previous marketing campaign (categorical: "unknown","other","failure","success")\n\n  Output variable (desired target):\n  17 - y - has the client subscribed a term deposit? (binary: "yes","no")\n', 'citation': None}}
           name     role         type      demographic  \
0           age  Feature      Integer              Age
1           job  Feature  Categorical       Occupation
2       marital  Feature  Categorical   Marital Status
3     education  Feature  Categorical  Education Level
4       default  Feature       Binary              NaN
5       balance  Feature      Integer              NaN
6       housing  Feature       Binary              NaN
7          loan  Feature       Binary              NaN
8       contact  Feature  Categorical              NaN
9   day_of_week  Feature         Date              NaN
10        month  Feature         Date              NaN
11     duration  Feature      Integer              NaN
12     campaign  Feature      Integer              NaN
13        pdays  Feature      Integer              NaN
14     previous  Feature      Integer              NaN
15     poutcome  Feature  Categorical              NaN
16            y   Target       Binary              NaN

                                          description  units missing_values
0                                                 NaN    NaN             no
1   type of job (categorical: 'admin.','blue-colla...    NaN             no
2   marital status (categorical: 'divorced','marri...    NaN             no
3   (categorical: 'basic.4y','basic.6y','basic.9y'...    NaN             no
4                              has credit in default?    NaN             no
5                              average yearly balance  euros             no
6                                   has housing loan?    NaN             no
7                                  has personal loan?    NaN             no
8   contact communication type (categorical: 'cell...    NaN            yes
9                        last contact day of the week    NaN             no
10  last contact month of year (categorical: 'jan'...    NaN             no
11   last contact duration, in seconds (numeric). ...    NaN             no
12  number of contacts performed during this campa...    NaN             no
13  number of days that passed by after the client...    NaN            yes
14  number of contacts performed before this campa...    NaN             no
15  outcome of the previous marketing campaign (ca...    NaN            yes
16          has the client subscribed a term deposit?    NaN             no

In [50]:
x.info()

<class 'pandas.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   age          45211 non-null  int64
 1   job          44923 non-null  str
 2   marital      45211 non-null  str
 3   education    43354 non-null  str
 4   default      45211 non-null  str
 5   balance      45211 non-null  int64
 6   housing      45211 non-null  str
 7   loan         45211 non-null  str
 8   contact      32191 non-null  str
 9   day_of_week  45211 non-null  int64
 10  month        45211 non-null  str
 11  duration     45211 non-null  int64
 12  campaign     45211 non-null  int64
 13  pdays        45211 non-null  int64
 14  previous     45211 non-null  int64
 15  poutcome     8252 non-null   str
dtypes: int64(7), str(9)
memory usage: 7.3 MB

In [51]:
from sklearn.model_selection import train_test_split,KFold,cross_val_score
from sklearn.preprocessing import LabelEncoder,MinMaxScaler
from sklearn.tree import DecisionTreeClassifier

In [52]:
x

,age,job,marital,education,default,balance,housing,loan,contact,day_of_week,month,duration,campaign,pdays,previous,poutcome
0,58,management,married,tertiary,no,2143,yes,no,NaN,5,may,261,1,-1,0,NaN
1,44,technician,single,secondary,no,29,yes,no,NaN,5,may,151,1,-1,0,NaN
2,33,entrepreneur,married,secondary,no,2,yes,yes,NaN,5,may,76,1,-1,0,NaN
3,47,blue-collar,married,NaN,no,1506,yes,no,NaN,5,may,92,1,-1,0,NaN
4,33,NaN,single,NaN,no,1,no,no,NaN,5,may,198,1,-1,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,no,825,no,no,cellular,17,nov,977,3,-1,0,NaN
45207,71,retired,divorced,primary,no,1729,no,no,cellular,17,nov,456,2,-1,0,NaN
45208,72,retired,married,secondary,no,5715,no,no,cellular,17,nov,1127,5,184,3,success
45209,57,blue-collar,married,secondary,no,668,no,no,telephone,17,nov,508,4,-1,0,NaN
45210,37,entrepreneur,married,secondary,no,2971,no,no,cellular,17,nov,361,2,188,11,other

In [53]:
y

         y
0       no
1       no
2       no
3       no
4       no
...    ...
45206  yes
45207  yes
45208  yes
45209   no
45210   no

[45211 rows x 1 columns]

In [54]:
x.isnull().sum()

age                0
job              288
marital            0
education       1857
default            0
balance            0
housing            0
loan               0
contact        13020
day_of_week        0
month              0
duration           0
campaign           0
pdays              0
previous           0
poutcome       36959
dtype: int64

In [55]:
y.isnull().sum()

y    0
dtype: int64

In [56]:
x.shape

(45211, 16)

In [57]:
y.shape

(45211, 1)

In [58]:
x.drop_duplicates()

,age,job,marital,education,default,balance,housing,loan,contact,day_of_week,month,duration,campaign,pdays,previous,poutcome
0,58,management,married,tertiary,no,2143,yes,no,NaN,5,may,261,1,-1,0,NaN
1,44,technician,single,secondary,no,29,yes,no,NaN,5,may,151,1,-1,0,NaN
2,33,entrepreneur,married,secondary,no,2,yes,yes,NaN,5,may,76,1,-1,0,NaN
3,47,blue-collar,married,NaN,no,1506,yes,no,NaN,5,may,92,1,-1,0,NaN
4,33,NaN,single,NaN,no,1,no,no,NaN,5,may,198,1,-1,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,no,825,no,no,cellular,17,nov,977,3,-1,0,NaN
45207,71,retired,divorced,primary,no,1729,no,no,cellular,17,nov,456,2,-1,0,NaN
45208,72,retired,married,secondary,no,5715,no,no,cellular,17,nov,1127,5,184,3,success
45209,57,blue-collar,married,secondary,no,668,no,no,telephone,17,nov,508,4,-1,0,NaN
45210,37,entrepreneur,married,secondary,no,2971,no,no,cellular,17,nov,361,2,188,11,other

In [59]:
import warnings
warnings.filterwarnings('ignore')

In [60]:
x['job']= x['job'].fillna(x['job'].mode()[0],inplace=True)

In [61]:
x['education'] = x['education'].fillna(x['education'].mode()[0],inplace=True)

In [62]:
x

,age,job,marital,education,default,balance,housing,loan,contact,day_of_week,month,duration,campaign,pdays,previous,poutcome
0,58,management,married,tertiary,no,2143,yes,no,NaN,5,may,261,1,-1,0,NaN
1,44,technician,single,secondary,no,29,yes,no,NaN,5,may,151,1,-1,0,NaN
2,33,entrepreneur,married,secondary,no,2,yes,yes,NaN,5,may,76,1,-1,0,NaN
3,47,blue-collar,married,secondary,no,1506,yes,no,NaN,5,may,92,1,-1,0,NaN
4,33,blue-collar,single,secondary,no,1,no,no,NaN,5,may,198,1,-1,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,no,825,no,no,cellular,17,nov,977,3,-1,0,NaN
45207,71,retired,divorced,primary,no,1729,no,no,cellular,17,nov,456,2,-1,0,NaN
45208,72,retired,married,secondary,no,5715,no,no,cellular,17,nov,1127,5,184,3,success
45209,57,blue-collar,married,secondary,no,668,no,no,telephone,17,nov,508,4,-1,0,NaN
45210,37,entrepreneur,married,secondary,no,2971,no,no,cellular,17,nov,361,2,188,11,other

In [63]:
x.isnull().sum()

age                0
job                0
marital            0
education          0
default            0
balance            0
housing            0
loan               0
contact        13020
day_of_week        0
month              0
duration           0
campaign           0
pdays              0
previous           0
poutcome       36959
dtype: int64

In [64]:
x.drop(columns=['poutcome','contact'],inplace=True)

In [65]:
x.columns

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'day_of_week', 'month', 'duration', 'campaign', 'pdays',
       'previous'],
      dtype='str')

In [66]:
scaler = MinMaxScaler()
x[['age','balance','duration']] = scaler.fit_transform(x[['age','balance','duration']])

In [67]:
x

,age,job,marital,education,default,balance,housing,loan,day_of_week,month,duration,campaign,pdays,previous
0,0.519481,management,married,tertiary,no,0.092259,yes,no,5,may,0.053070,1,-1,0
1,0.337662,technician,single,secondary,no,0.073067,yes,no,5,may,0.030704,1,-1,0
2,0.194805,entrepreneur,married,secondary,no,0.072822,yes,yes,5,may,0.015453,1,-1,0
3,0.376623,blue-collar,married,secondary,no,0.086476,yes,no,5,may,0.018707,1,-1,0
4,0.194805,blue-collar,single,secondary,no,0.072812,no,no,5,may,0.040260,1,-1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,0.428571,technician,married,tertiary,no,0.080293,no,no,17,nov,0.198658,3,-1,0
45207,0.688312,retired,divorced,primary,no,0.088501,no,no,17,nov,0.092721,2,-1,0
45208,0.701299,retired,married,secondary,no,0.124689,no,no,17,nov,0.229158,5,184,3
45209,0.506494,blue-collar,married,secondary,no,0.078868,no,no,17,nov,0.103294,4,-1,0
45210,0.246753,entrepreneur,married,secondary,no,0.099777,no,no,17,nov,0.073404,2,188,11

In [68]:
lab_enc = LabelEncoder()

In [69]:
import joblib
col =['housing','loan','month','default','education','marital','job']
encoder ={}
for i in col:
    x[i] = lab_enc.fit_transform(x[i])
    encoder[i] = lab_enc
x

,age,job,marital,education,default,balance,housing,loan,day_of_week,month,duration,campaign,pdays,previous
0,0.519481,4,1,2,0,0.092259,1,0,5,8,0.053070,1,-1,0
1,0.337662,9,2,1,0,0.073067,1,0,5,8,0.030704,1,-1,0
2,0.194805,2,1,1,0,0.072822,1,1,5,8,0.015453,1,-1,0
3,0.376623,1,1,1,0,0.086476,1,0,5,8,0.018707,1,-1,0
4,0.194805,1,2,1,0,0.072812,0,0,5,8,0.040260,1,-1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,0.428571,9,1,2,0,0.080293,0,0,17,9,0.198658,3,-1,0
45207,0.688312,5,0,0,0,0.088501,0,0,17,9,0.092721,2,-1,0
45208,0.701299,5,1,1,0,0.124689,0,0,17,9,0.229158,5,184,3
45209,0.506494,1,1,1,0,0.078868,0,0,17,9,0.103294,4,-1,0
45210,0.246753,2,1,1,0,0.099777,0,0,17,9,0.073404,2,188,11

In [70]:
print(encoder)

{'housing': LabelEncoder(), 'loan': LabelEncoder(), 'month': LabelEncoder(), 'default': LabelEncoder(), 'education': LabelEncoder(), 'marital': LabelEncoder(), 'job': LabelEncoder()}

In [71]:
joblib.dump(encoder,open("encoder.pkl", "wb"))

In [72]:
y_enc = LabelEncoder()
y= y_enc.fit_transform(y['y'])
y

array([0, 0, 0, ..., 1, 0, 0], shape=(45211,))

In [73]:
joblib.dump(y_enc,open("y.pkl", "wb"))

In [74]:
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.3)

In [75]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((31647, 14), (13564, 14), (31647,), (13564,))

In [76]:
dtc_model = DecisionTreeClassifier()

In [77]:
kfold = KFold(n_splits=5)
vali_score = cross_val_score(
    dtc_model,X_train,y_train,cv=kfold
)

In [78]:
print(vali_score.mean()*100)
print(vali_score)

86.6812258923978
[0.86682464 0.85924171 0.8668036  0.87565176 0.86553958]

In [79]:
dtc_model.fit(X_train,y_train)

DecisionTreeClassifier()

In [80]:
y_pred = dtc_model.predict(X_test)
y_pred[:10]

array([0, 0, 0, 1, 0, 1, 0, 0, 0, 0])

In [81]:
y_test[:10]

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 1])

In [82]:
from sklearn.metrics import accuracy_score,confusion_matrix
print(accuracy_score(y_test,y_pred))

0.8659687407844294

In [83]:
print(confusion_matrix(y_test,y_pred))

[[11044   920]
 [  898   702]]

In [84]:
joblib.dump(dtc_model,'Dtc_model.pkl')

['Dtc_model.pkl']

In [85]:
x.columns

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'day_of_week', 'month', 'duration', 'campaign', 'pdays',
       'previous'],
      dtype='str')

In [86]:
x

,age,job,marital,education,default,balance,housing,loan,day_of_week,month,duration,campaign,pdays,previous
0,0.519481,4,1,2,0,0.092259,1,0,5,8,0.053070,1,-1,0
1,0.337662,9,2,1,0,0.073067,1,0,5,8,0.030704,1,-1,0
2,0.194805,2,1,1,0,0.072822,1,1,5,8,0.015453,1,-1,0
3,0.376623,1,1,1,0,0.086476,1,0,5,8,0.018707,1,-1,0
4,0.194805,1,2,1,0,0.072812,0,0,5,8,0.040260,1,-1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,0.428571,9,1,2,0,0.080293,0,0,17,9,0.198658,3,-1,0
45207,0.688312,5,0,0,0,0.088501,0,0,17,9,0.092721,2,-1,0
45208,0.701299,5,1,1,0,0.124689,0,0,17,9,0.229158,5,184,3
45209,0.506494,1,1,1,0,0.078868,0,0,17,9,0.103294,4,-1,0
45210,0.246753,2,1,1,0,0.099777,0,0,17,9,0.073404,2,188,11